# Generated by Django 2.2.3 on 2019-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Метка категории')),
                ('category_descr', models.CharField(default='', max_length=150, verbose_name='Описание категории')),
                ('plus_keywords', models.TextField(verbose_name='Плюс-слова')),
                ('minus_keywords', models.TextField(verbose_name='Минус-слова')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория и ключевые слова',
                'verbose_name_plural': 'Категории и ключевые слова',
                'db_table': 'keyword',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(unique=True)),
                ('customer', models.TextField()),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('url_addr', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'db_table': 'tenders',
                'ordering': ('number',),
            },
        ),
    ]
